site_name: Financial Analysis Agent
site_description: Documentation for the AI-Powered Financial Analysis Agent
site_author: Development Team

# Repository
repo_name: Financial Analysis Agent
repo_url: https://github.com/tan-yong-sheng/financial-analysis-agent

# Theme configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - footnotes
  - toc:
      permalink: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: getting-started.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quickstart.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Architecture:
    - Overview: architecture.md
    - Agent System: components/agent-system.md
    - Citation System: components/citation-system.md
  - Agents:
    - Overview: agents/overview.md
    - Data Collection Agent: agents/data_collection_agent.md
    - Research Agent: agents/research_agent.md
    - Analysis Agent: agents/analysis_agent.md
    - Report Agent: agents/report_agent.md
    - Fact Check Agent: agents/fact_check_agent.md
    - Planner Agent: agents/planner_agent.md
  - Tools:
    - Overview: tools/index.md
    - Data Transformer: tools/data_transformer.md
    - Financial Data Provider: tools/financial_data_provider.md
    - Web Research: tools/web_research.md
  - Testing:
    - Overview: testing/index.md
    - Writing Tests: testing/writing-tests.md
    - Coverage: testing/coverage.md
  - Guides:
    - Usage: usage.md
    - Testing: guides/testing.md
    - Observability: guides/observability.md
    - Customization: guides/customization.md
    - Citation Guidelines: citation_guidelines.md
  - API Reference:
    - Agents API: api/agents.md
    - Tools API: api/tools.md
    - Complete Reference: api-reference.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
  - Contributing: contributing.md
